name: nn-benchmark
channels:
  - pytorch
  - defaults
  - gpytorch
dependencies:
  - python=3.8
  - scipy
  - pytorch=1.7.1
  - nodejs
  - matplotlib
  - jupyterlab
  - ipywidgets
  - numpy
  - scikit-learn
  - pandas
  - joblib
  - numba
  - gpytorch
  - git
  - pip
  - pip:
    - '--find-links=https://pytorch-geometric.com/whl/torch-1.7.0+cpu.html'
    - torch-scatter
    - torch-sparse
    - torch-cluster
    - torch-spline-conv
    - torch-geometric
