name: nn-benchmark
channels:
  - pytorch
  - defaults
dependencies:
  - absl-py
  - python=3.8
  - scipy
  - pytorch
  - cudatoolkit=10.1
  - nodejs
  - matplotlib
  - jupyterlab
  - ipywidgets
  - numpy
