name: nn-benchmark
channels:
  - pytorch
  - defaults
  - gpytorch
dependencies:
  - python=3.8
  - scipy
  - pytorch=1.7.1
  - cudatoolkit=11.0
  - nodejs
  - matplotlib
  - jupyterlab
  - ipywidgets
  - numpy
  - scikit-learn
  - pandas
  - gpytorch
  - git
